# Generated by Django 5.0.6 on 2024-05-30 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_alter_review_content_alter_review_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="business_license",
            field=models.FileField(blank=True, null=True, upload_to="licenses/"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
